export const LOADING = 'LOADING';
export const LOADING_DONE = 'LOADING_DONE';

export const NEWS_LOADING = 'NEWS_LOADING';
export const SOURCE_LOADING = 'SOURCE_LOADING';
export const HEADLINE_LOADING = 'HEADLINE_LOADING';

export const HEADLINE_LIST = 'HEADLINE_LIST';
export const SOURCES_LIST = 'SOURCES_LIST';
export const NEWS_LIST = 'NEWS_LIST';